# Generated by Django 3.1.7 on 2021-03-26 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=15)),
                ('apikey', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BcoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_email', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_first_name', to=settings.AUTH_USER_MODEL)),
                ('groups', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_last_name', to=settings.AUTH_USER_MODEL)),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_password', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
