// src/views/home/HomeView/Specification.js

import React from 'react';
import { Card,
	CardActionArea,
	CardActions,
	CardContent,
	makeStyles,
	Typography
}from '@material-ui/core';

// Routing to pages
import { Link as RouterLink } from 'react-router-dom';

const useStyles = makeStyles({
  root: {
    minWidth: 275,
  },
  bullet: {
    display: 'inline-block',
    margin: '0 2px',
    transform: 'scale(0.8)',
  },
  linkCard: {
      minHeight: '300px',
      textAlign: 'center'
  },
  title: {
    fontSize: '33px',
  },
  pos: {
    marginBottom: 12,
  },
});

export default function Specification() {
  const classes = useStyles();
  const ieeeLink = 'https://standards.ieee.org/standard/2791-2020.html'
  var ieee = require('src/images/ieee.jpg')

  return (
    <Card className={classes.root, classes.linkCard}>
      <CardActionArea onClick={() => window.open(ieeeLink)}>
        <CardContent className={classes.linkCard} >
            <Typography className={classes.title}>
            IEEE 2791-2020
            </Typography>
            <Typography className={classes.bullet}>
              IEEE Standard for Bioinformatics Analyses 
	  Generated by High-Throughput Sequencing (HTS) to Facilitate Communication
            <br/><br/><img src={ieee} width={150} alt="IEEE logo"/>
            </Typography>
        </CardContent>
      </CardActionArea>
    </Card>
  );
}
